[background-color="#303030"]
= Kubernetes Ingress 
Hello-World sample

[background-color="#326de6"]
== kubernetes concepts

[background-color="#326de6"]
=== pod
* atomic building block
* one or more container
* colocated, shared ports, shared volumes
* mortal: they are born and they die

[background-color="#326de6"]
=== node
* pods run on nodes
* worker machine

[background-color="#326de6"]
=== service
* cluster internal abstraction to access set of pods
* unique name 
* labels & selectors: e.g. "release" : "stable", "environment" : "dev"
* virtual ip, port
* routing by iptables, kube-proxy

[background-color="#326de6"]
=== deployment
* describe how pods should run
* desired count of replicas
* labels & selectors
* update strategy

[background-color="#326de6"]
=== ingress
* manages external access to the services in a cluster
* mostly http based
* ssl termination
* load balancing
* name based virtual hosting

[background-color="#326de6"]
=== other controllers
* ReplicationController / Replica Sets
* IngressController
* Deployment controller

[background-color="#326de6"]
=== ConfigMaps
* inject containers with configuration data
 * by command line
 * environment variables
 * volume
* name/value pairs or entire config files

[background-color="#326de6"]
=== secrets
* similar to ConfigMaps, more restricted
* name/value pairs, no entire config file

[background-color="#326de6"]
=== other concepts
* annotations: like labels, but "non-identifying metadata"
* namespaces: allows multiple virtual clusters in the same physical cluster

[background-color="#09c1d1"]
== live demo

* minikube is a docker environment
* secrets
* ingress

=== minikube startup
:source-highlighter: highlightjs
[source,bash]
----
sudo minikube start

# optional: cleanup of previous try:
sudo minikube addons disable ingress
kubectl delete deployment,service echoserver
kubectl delete deployment,service munich
kubectl delete deployment,service paris
kubectl delete ingress kubernetes-ingress-hello-world
kubectl delete secret tls-certificate
----

=== minikube docker enironment
:source-highlighter: highlightjs
[source,bash]
----
eval $(sudo minikube docker-env)
docker build -t hello-service hello-service/ 
docker run -ti hello-service
----

=== create pods & services
:source-highlighter: highlightjs
[source,bash]
----
kubectl run echoserver --image=gcr.io/google_containers/echoserver:1.4 --port=8080
kubectl expose deployment echoserver --type=NodePort
# sudo minikube service echoserver

kubectl run munich --image=hello-service:latest --image-pull-policy=Never --env="GREETINGS=grias-eich" --port=80
kubectl expose deployment munich --type=NodePort
# sudo minikube service munich

kubectl run paris --image=hello-service:latest --image-pull-policy=Never --env="GREETINGS=bonjour" --port=80
kubectl expose deployment paris --type=NodePort
# sudo minikube service paris
----

=== create secrets
:source-highlighter: highlightjs
[source,bash]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -config <(
cat <<-EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn
x509_extensions = req_ext

[ dn ]
CN = greetings.toall
C = DE
ST = BY
L = Munich
O = Muenchhausen
OU = Muenchhausen

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = greetings.toall
DNS.2 = munich.greetings.toall
DNS.3 = paris.greetings.toall
EOF
)

kubectl create secret tls tls-certificate --key /tmp/tls.key --cert /tmp/tls.crt
----


=== create ingress
:source-highlighter: highlightjs
[source,bash]
----
sudo minikube addons enable ingress
kubectl create --validate=false -f kubernetes-ingress-hello-world.yaml
# kubectl describe ing kubernetes-ingress-hello-world

# echo "$(sudo minikube ip) echo.toall greetings.toall paris.greetings.toall munich.greetings.toall" | sudo tee -a /etc/hosts

# kubectl get pods --all-namespaces --watch
# kubectl scale deployment munich --replicas=3

----

[background-color="#09c1d1"]
== alternatives
other ingress controllers

* kubernetes/ingress-nginx 	
* nginxinc/kubernetes-ingress with NGINX 	
* nginxinc/kubernetes-ingress with NGINX Plus 	
* haproxy based (upcomming)		

https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md[source]

[background-color="#c9e9ec"]
== recommended readings
* https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/[kubectl for docker users]
* https://github.com/kubernetes/ingress-nginx/tree/master/deploy#minikube[kubernetes howto: nginx ingress]
* https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md[nginx howto: own ingress controller]
* https://medium.com/@Oskarr3/setting-up-ingress-on-minikube-6ae825e98f82[howto: setting up ingress on minikube]
* https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tls[howto: nginx ingress ssl termination]
* https://github.com/kubernetes/ingress-nginx/issues/1374[issue: nginx ingress certificate]
* https://daemonza.github.io/2017/02/13/kubernetes-nginx-ingress-controller/[howto: Kubernetes nginx-ingress-controller]